### ISSUE TITLE
Admin New expedition entry not working correctly

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemAdmin2#10]
Bai--When I tried to enter two new expeditions into Admin I discovered a problem:

I added the first expedition: AAR2011 and the DB gave it nr 81923
When I tried to add the second expedition: AAR2013, the DB tried to give it the same number and of course the DB will not add another expedition under the same nr.
I have included 2 screenshots
![screen shot 2019-02-01 at 12 22 56 pm](https://user-images.githubusercontent.com/43789398/52141452-cc9c0a80-2623-11e9-8aeb-6cb9fd04b9ed.png)
![screen shot 2019-02-01 at 12 22 16 pm](https://user-images.githubusercontent.com/43789398/52141453-cc9c0a80-2623-11e9-8f45-0d1501dd9700.png)

**Comment by annikakj** [comment]
![screen shot 2019-02-01 at 12 22 16 pm](https://user-images.githubusercontent.com/43789398/52141485-e3daf800-2623-11e9-9c96-0d939395d7ae.png)

**Comment by annikakj** [comment]
![screen shot 2019-02-01 at 12 22 56 pm](https://user-images.githubusercontent.com/43789398/52141508-f2c1aa80-2623-11e9-82a7-96776b9109c6.png)

**Comment by bhchen8** [comment]
I addad "AAR2013" without problem.   We cannot continue add expedition.
After adding first expedition, the popup window have be closed, then click
"New" button to add second expedition.

**Comment by bhchen8** [comment]
[image: image.png]

**Comment by annikakj** [comment]
Close ticket. Will see if same problem happens again next time adding more than one expeditions

**Comment by klehnert55** [comment]
We need to change the code. It is non-intuitive that I window needs to be closed before you can add another expedition.
When you design an application, it is essential to carefully consider usability. 
Annika's problem with the entry of expeditions should be considered 'usability test results', and need to lead to decisions and improvements to overcome such usability problems.

**Comment by bhchen8** [comment]
I will improve the interface.
