### ISSUE TITLE
Specimen with multiple stations in check view need to order by specimen num

### ISSUE THREAD

**Issue by sparkji** [iedadata/EarthChemAdmin2#11]
http://ecstage.earthchem.org:8080/EarthChemDataTool/faces/ECAdmin.xhtml
example: 
Specimen 27911 has been linked two stations, one is 1966, another is 1965, but first relationships show in the first row, the second one show in the last row. It is not easy for curator to decide which relationship should be deleted.
So, please order the list by specimen_num. And should auto refresh the list after delete action happend.

![image](https://user-images.githubusercontent.com/8258431/52888172-b1172080-3148-11e9-9839-0cbd047e81f5.png)

![image](https://user-images.githubusercontent.com/8258431/52888189-bf653c80-3148-11e9-9e80-22337131b420.png)

**Comment by sparkji** [comment]
I see it refreshes after delete action. Just add ordering by specimen_num

**Comment by bhchen8** [comment]
fixed
