### ISSUE TITLE
Admin does not allow entry of DOI to refs without DOI

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemAdmin2#12]
Old papers in PetDb do not all have DOI. Today I found a DOI for ref 894 (10.1130/0016-7606(1970)81[895:gftmrn]2.0.co;2) and attempted to add it. Admin does not save it.

**Comment by annikakj** [comment]
@Bai, tried adding doi to refs that were missing doi and the Admin does not save the information. e.g, tried adding doi 10.1086/628443 to ref 3604.

**Comment by bhchen8** [comment]
the bug is fixed, please test it.

**Comment by annikakj** [comment]
Confirmed the issue is fixed.
