### ISSUE TITLE
Doi error 

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemAdmin2#15]
Can you check why I get this error  for this doi:
10.1016/j.epsl.2019.03.011

Error!ERROR: null value in column "citation_num" violates not-null constraint Detail: Failing row contains (null, SOURCES VS PROCESSES: UNRAVELING THE COMPOSITIONAL HETEROGENEITY..., Elsevier BV, 2019, null, EARTH AND PLANETARY SCIENCE LETTERS, null, 514, null, null, null, null, null, 1, Paul Béguelin, Michael Bizimis, Eleanor C. McIntosh, Brian Cous..., 119-129).

**Comment by sparkji** [comment]
I have input it from http://ecstage.earthchem.org:8080/EarthChemDataTool/faces/ECAdmin.xhtml, the citation_num is 3886. Please check it.

Seems you use the admin on grg-doc1.ldeo.columbia.edu, it still some problems, I am working on it.

**Comment by annikakj** [comment]
I’m sorry Peng I don’t quite understand what I am supposed to do. Can you explain again?

**Comment by sparkji** [comment]
It recorded the issue you reported. Now we have two admin tool, one on ecstage server, another is on grg-doc1 server
I found the log for admin tool on server http://grg-doc1.ldeo.columbia.edu:8080/EarthChemDataTool/faces/ECAdmin.xhtml
So I think you used the admin on grg-doc1.

**Comment by annikakj** [comment]
I have checked now and the  reference is now entered for that doi as it should be. Thank you.
