### ISSUE TITLE
Add author checking at tab 'Check View'

### ISSUE THREAD

**Issue by sparkji** [iedadata/EarthChemAdmin2#17]
Create new block 'Reference without authors'
### Just show column 'citation_num','title', and add a button 'Add Authors', direct to page 'Edit citation'.

**Comment by bhchen8** [comment]
There are only two citations, 3529 and 3705 without authors.  The following query was used for checking:
select c.citation_num
from ec_status_info e, citation c
where e.data_status in ('COMPLETED','DATA_LOADED') and e.citation_num = c.citation_num and c.citation_num not in 
(select c.citation_num 
from ec_status_info e, citation c, author_list a
where e.data_status in ('COMPLETED','DATA_LOADED') and e.citation_num = c.citation_num and e.citation_num = a.citation_num
)

**Comment by bhchen8** [comment]
Updated.  Please test it.
