### ISSUE TITLE
Add a tab to show content of table entity_statistics

### ISSUE THREAD

**Issue by sparkji** [iedadata/EarthChemAdmin2#2]
![image](https://user-images.githubusercontent.com/8258431/48718448-689fa380-ebe9-11e8-8017-2044528e7a9e.png)

**Comment by annikakj** [comment]
I think we should show the statistics in the same format as is currently being shown in PetDB
![screen shot 2018-11-19 at 11 33 30 am](https://user-images.githubusercontent.com/43789398/48720999-f8941c00-ebee-11e8-946c-de75ff1c349d.png)

**Comment by bhchen8** [comment]
Please test it

**Comment by sparkji** [comment]
Great, thanks!
