### ISSUE TITLE
Admin does not allow edit of Sampling Feature after previous edit pop-up

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemAdmin2#21]
When making an edit of e.g. a station (Sampling Feature) in Admin, a pop-up window appears where the edits are made. They are then saved. If DM then tries to search for another station to edit the Admin tool does not respond. The only way to get to to ability to edit is by opening a new tab with the Admin url, or by reloading the browser window. This occurs in both Google Chrom and Firefox.
![Screen Shot 2019-06-25 at 12 10 37 PM](https://user-images.githubusercontent.com/43789398/60114663-443d1400-9742-11e9-939e-53c944b37b7b.png)

**Comment by bhchen8** [comment]
The bug is fixd

**Comment by annikakj** [comment]
Tested, issue is closed.
