### ISSUE TITLE
Add function (check one sample with multiple station) on check view

### ISSUE THREAD

**Issue by sparkji** [iedadata/EarthChemAdmin2#4]
related issue https://github.com/iedadata/EarthChemAdmin2/issues/3
Lot of time, sheetLoader did not clean up the old relationship between specimen and station when reload a paper. 
eg.
table: related_feature
related_feature_num   sampling_feature_num      relationship_type_num   related_sampling_feature_num
682134	                                   701583(HK1955AG)                         22	                             701641(PUNA BASALT)
682074                                       701583(HK1955AG)                           22                               701569(HK1955AG)
The function should show specimen code and station code, allow curation to determine which relationship should be deleted.
I have ticket on [sheetLoader](https://github.com/iedadata/EarthChemODM2TemplateReader/issues/3), but seems it does not be fixed. So, please add this function on ecdb-admin, like below
![image](https://user-images.githubusercontent.com/8258431/49630004-50d26880-f9ba-11e8-8cf0-af586bafdec2.png)

**Comment by sparkji** [comment]
try this query to get specimen with multiple stations
select * from related_feature where sampling_feature_num in 
select sampling_feature_num from (
  SELECT *,
  ROW_NUMBER() OVER(PARTITION BY sampling_feature_num, relationship_type_num) AS Row
  FROM related_feature where relationship_type_num=22
) dups
where 
dups.Row > 1

**Comment by sparkji** [comment]
If a specimen linked two stations, curator has delete one relationship, want to delete another one, should be prevented

**Comment by bhchen8** [comment]
I run the query above and get error:

ERROR: ERROR: syntax error at or near "select"
  Position: 61

**Comment by sparkji** [comment]
just use
select sampling_feature_num from (
SELECT *,
ROW_NUMBER() OVER(PARTITION BY sampling_feature_num, relationship_type_num) AS Row
FROM related_feature where relationship_type_num=22
) dups
where
dups.Row > 1

**Comment by bhchen8** [comment]
I used  "select sampling_feature_num from related_feature where relationship_type_num = 22 group by sampling_feature_num having count(*) > 1"

**Comment by sparkji** [comment]
It's fine, just want to save your time.

**Comment by bhchen8** [comment]
query for view:
select r.related_feature_num, c.sampling_feature_num, c.sampling_feature_code, p.sampling_feature_num, p.sampling_feature_code, r.relationship_type_num
from related_feature r, sampling_feature c, sampling_feature p 
where r.sampling_feature_num = c.sampling_feature_num and p.sampling_feature_num = r.related_sampling_feature_num and c.sampling_feature_num in 
(select sampling_feature_num from related_feature where relationship_type_num = 22 group by sampling_feature_num having count(*) > 1)

**Comment by bhchen8** [comment]
updated, please test it.

**Comment by annikakj** [comment]
@bhchen8 Is there something for me to do on this ticket?

**Comment by sparkji** [comment]
@annikakj You need not do anything now. Let's discuss these new functions after AGU.
