### ISSUE TITLE
Add function 'delete orphan sampling feature' on check view

### ISSUE THREAD

**Issue by sparkji** [iedadata/EarthChemAdmin2#5]
'Check view' just show orphan sampling feature, like station without child, specimen without child, etc.
Please add delete function, allow curator delete orphan sampling features.
And, please change 'No Child Station' to 'Station without child', 'No Parent Analyzed' to 'Analyzed sample without parent',  'No Child Specimen' to 'Specimen without child', 'No Parent Specimen' to 'Specimen without parent.

**Comment by bhchen8** [comment]
In which table, view or original table,  data should be deleted?

**Comment by sparkji** [comment]
Original table

**Comment by bhchen8** [comment]
updated, please test it.

**Comment by sparkji** [comment]
we don't have table sampling_feature_extension_property any more, please remove it from queries.

**Comment by bhchen8** [comment]
updated code and drop this table from jdbc:postgresql://dev-ecdb-vm.earthchem.org:5432/ecdb_v1

**Comment by sparkji** [comment]
@bhchen8 Great! Thanks.
